package lk.ijse.asms.util;

public enum Routes {
    LOGIN,MANAGER_DASHBOARD,ADMIN_DASHBOARD,ADD_CUSTOMER,UPDATE_CUSTOMER, STORE_MANAGE, PAYMENT_MANAGE, JOB_MANAGE, VEHICLE_MANAGE, EMPLOYEE_MANAGE, CALL_JOB, FINISH_JOB, DELETE_VEHICLE, UPDATE_EMPLOYEE, DELETE_EMPLOYEE, ADD_JOB,SALARY_PAYMENT, ADD_EMPLOYEE, CONTRACT_PAYMENT,
    SALARY_PLANE_UPDATE, POINT_PAYMENT_PLANE_UPDATE, JOB_REPORT,
}
